---
  - name: Atualizar cache e pacotes no Ubuntu
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Atualizar cache e pacotes no Rocky
    ansible.builtin.yum:
      update_cache: yes
      upgrade: dist
    when: ansible_facts['distribution'] == "Rocky"